//
//  NoZ - Copyright(c) 2026 NoZ Games, LLC
//

namespace NoZ.Editor;

public static class AssetManifest
{
    public static void Generate(EditorConfig config)
    {
        if (config.GenerateCs != null)
            GenerateCs(config);

        if (config.GenerateLua != null)
            GenerateLua(config);
    }

    private static string Pluralize(string typeName)
    {
        if (typeName.EndsWith("s", StringComparison.Ordinal))
            return typeName + "es";
        return typeName + "s";
    }

    private static void GenerateCs(EditorConfig config)
    {
        var path = config.GenerateCs!;
        Directory.CreateDirectory(Path.GetDirectoryName(path) ?? ".");

        using var writer = new StreamWriter(path);

        writer.WriteLine("//");
        writer.WriteLine("//  Auto-generated by NoZ Editor - DO NOT EDIT");
        writer.WriteLine("//");
        writer.WriteLine();
        writer.WriteLine("using NoZ;");
        writer.WriteLine();
        writer.WriteLine($"namespace {config.CsNamespace};");
        writer.WriteLine();
        writer.WriteLine($"public static class {config.CsClass}");
        writer.WriteLine("{");

        var documentsByType = DocumentManager.Documents
            .Where(d => !d.IsEditorOnly)
            .GroupBy(d => d.Def.Type)
            .OrderBy(g => g.Key.ToString())
            .ToList();

        var hasAtlases = documentsByType.Any(g => g.Key == AssetType.Atlas);

        // Names class
        writer.WriteLine("    public static class Names");
        writer.WriteLine("    {");
        foreach (var group in documentsByType)
        {
            foreach (var doc in group.OrderBy(d => d.Name))
            {
                var constName = ToPascalCase(doc.Name);
                writer.WriteLine($"        public const string {constName} = \"{doc.Name}\";");
            }
        }
        writer.WriteLine("    }");

        // Static fields grouped by type
        foreach (var group in documentsByType)
        {
            var typeName = group.Key.ToString();
            var pluralName = Pluralize(typeName);
            var runtimeType = Asset.GetDef(group.Key)?.RuntimeType.Name ?? "Asset";

            writer.WriteLine();
            writer.WriteLine($"    public static class {pluralName}");
            writer.WriteLine("    {");
            foreach (var doc in group.OrderBy(d => d.Name))
            {
                var fieldName = ToPascalCase(doc.Name);
                writer.WriteLine($"        public static readonly {runtimeType} {fieldName} = {{ get; private set; }} = null!;");
            }
            writer.WriteLine("    }");
        }

        // AtlasArray field if we have atlases
        if (hasAtlases)
        {
            writer.WriteLine();
            writer.WriteLine("    public static Texture? AtlasArray { get; private set; }");
        }

        // LoadAssets method
        writer.WriteLine();
        writer.WriteLine("    public static void LoadAssets()");
        writer.WriteLine("    {");
        foreach (var group in documentsByType)
        {
            var typeName = group.Key.ToString();
            var pluralName = Pluralize(typeName);
            var runtimeType = Asset.GetDef(group.Key)?.RuntimeType.Name ?? "Asset";
            foreach (var doc in group.OrderBy(d => d.Name))
            {
                var fieldName = ToPascalCase(doc.Name);
                writer.WriteLine($"        {pluralName}.{fieldName} = ({runtimeType}?)Asset.Load(AssetType.{group.Key}, Names.{fieldName});");
            }
        }

        // Create texture array from atlases
        if (hasAtlases)
        {
            var atlasGroup = documentsByType.First(g => g.Key == AssetType.Atlas);
            var atlasNames = atlasGroup.OrderBy(d => d.Name).Select(d => $"Atlases.{ToPascalCase(d.Name)}").ToList();

            writer.WriteLine();
            writer.WriteLine("        // Create texture array from all atlases");
            writer.WriteLine($"        AtlasArray = Texture.CreateArray({string.Join(", ", atlasNames)});");
            writer.WriteLine("        Graphics.SpriteAtlas = AtlasArray;");
        }

        writer.WriteLine("    }");

        // ReloadAssets method
        writer.WriteLine();
        writer.WriteLine("    public static void ReloadAssets()");
        writer.WriteLine("    {");
        writer.WriteLine("        // TODO: hot reload");
        writer.WriteLine("    }");

        // UnloadAssets method
        writer.WriteLine();
        writer.WriteLine("    public static void UnloadAssets()");
        writer.WriteLine("    {");

        // Dispose AtlasArray first
        if (hasAtlases)
        {
            writer.WriteLine("        Graphics.SpriteAtlas = null;");
            writer.WriteLine("        AtlasArray?.Dispose();");
            writer.WriteLine("        AtlasArray = null;");
        }

        foreach (var group in documentsByType)
        {
            var typeName = group.Key.ToString();
            var pluralName = Pluralize(typeName);
            foreach (var doc in group.OrderBy(d => d.Name))
            {
                var fieldName = ToPascalCase(doc.Name);
                writer.WriteLine($"        {pluralName}.{fieldName}?.Dispose();");
            }
        }
        writer.WriteLine("    }");

        writer.WriteLine("}");

        Log.Info($"Generated {path}");
    }

    private static void GenerateLua(EditorConfig config)
    {
        var path = config.GenerateLua!;
        var className = config.LuaClass;

        Directory.CreateDirectory(Path.GetDirectoryName(path) ?? ".");

        using var writer = new StreamWriter(path);

        writer.WriteLine("--");
        writer.WriteLine("--  Auto-generated by NoZ Editor - DO NOT EDIT");
        writer.WriteLine("--");
        writer.WriteLine();
        writer.WriteLine($"local {className} = {{}}");
        writer.WriteLine();

        var documentsByType = DocumentManager.Documents
            .Where(d => !d.IsEditorOnly)
            .GroupBy(d => d.Def.Type)
            .OrderBy(g => g.Key.ToString());

        foreach (var group in documentsByType)
        {
            var typeName = group.Key.ToString();
            var pluralName = Pluralize(typeName);
            writer.WriteLine($"{className}.{pluralName} = {{");

            foreach (var doc in group.OrderBy(d => d.Name))
            {
                var constName = ToPascalCase(doc.Name);
                writer.WriteLine($"    {constName} = \"{doc.Name}\",");
            }

            writer.WriteLine("}");
            writer.WriteLine();
        }

        writer.WriteLine($"return {className}");

        Log.Info($"Generated {path}");
    }

    private static string ToPascalCase(string name)
    {
        var sb = new System.Text.StringBuilder();
        var capitalizeNext = true;

        foreach (var c in name)
        {
            if (c == '_' || c == '-' || c == ' ')
            {
                capitalizeNext = true;
            }
            else if (capitalizeNext)
            {
                sb.Append(char.ToUpperInvariant(c));
                capitalizeNext = false;
            }
            else
            {
                sb.Append(c);
            }
        }

        return sb.ToString();
    }
}
