//
//  NoZ - Copyright(c) 2026 NoZ Games, LLC
//

namespace NoZ.Editor;

public static class AssetManifest
{
    public static void Generate(EditorConfig config)
    {
        if (config.GenerateCs != null)
            GenerateCs(config);

        if (config.GenerateLua != null)
            GenerateLua(config);
    }

    private static void GenerateCs(EditorConfig config)
    {
        var path = config.GenerateCs!;
        Directory.CreateDirectory(Path.GetDirectoryName(path) ?? ".");

        using var writer = new StreamWriter(path);

        writer.WriteLine("//");
        writer.WriteLine("//  Auto-generated by NoZ Editor - DO NOT EDIT");
        writer.WriteLine("//");
        writer.WriteLine();
        writer.WriteLine($"namespace {config.CsNamespace};");
        writer.WriteLine();
        writer.WriteLine($"public static class {config.CsClass}");
        writer.WriteLine("{");

        var documentsByType = DocumentManager.Documents
            .Where(d => !d.IsEditorOnly)
            .GroupBy(d => d.Def.Type)
            .OrderBy(g => g.Key.ToString())
            .ToList();

        // Names class
        writer.WriteLine("    public static class Names");
        writer.WriteLine("    {");
        foreach (var group in documentsByType)
        {
            foreach (var doc in group.OrderBy(d => d.Name))
            {
                var constName = ToPascalCase(doc.Name);
                writer.WriteLine($"        public const string {constName} = \"{doc.Name}\";");
            }
        }
        writer.WriteLine("    }");

        // Static fields grouped by type
        foreach (var group in documentsByType)
        {
            var typeName = group.Key.ToString();
            var runtimeType = Asset.GetDef(group.Key)?.RuntimeType.Name ?? "Asset";

            writer.WriteLine();
            writer.WriteLine($"    public static class {typeName}s");
            writer.WriteLine("    {");
            foreach (var doc in group.OrderBy(d => d.Name))
            {
                var fieldName = ToPascalCase(doc.Name);
                writer.WriteLine($"        public static {runtimeType}? {fieldName};");
            }
            writer.WriteLine("    }");
        }

        // LoadAssets method
        writer.WriteLine();
        writer.WriteLine("    public static void LoadAssets()");
        writer.WriteLine("    {");
        foreach (var group in documentsByType)
        {
            var typeName = group.Key.ToString();
            var runtimeType = Asset.GetDef(group.Key)?.RuntimeType.Name ?? "Asset";
            foreach (var doc in group.OrderBy(d => d.Name))
            {
                var fieldName = ToPascalCase(doc.Name);
                writer.WriteLine($"        {typeName}s.{fieldName} = ({runtimeType}?)Asset.Load(AssetType.{group.Key}, Names.{fieldName});");
            }
        }
        writer.WriteLine("    }");

        // ReloadAssets method
        writer.WriteLine();
        writer.WriteLine("    public static void ReloadAssets()");
        writer.WriteLine("    {");
        writer.WriteLine("        // TODO: hot reload");
        writer.WriteLine("    }");

        // UnloadAssets method
        writer.WriteLine();
        writer.WriteLine("    public static void UnloadAssets()");
        writer.WriteLine("    {");
        foreach (var group in documentsByType)
        {
            var typeName = group.Key.ToString();
            foreach (var doc in group.OrderBy(d => d.Name))
            {
                var fieldName = ToPascalCase(doc.Name);
                writer.WriteLine($"        {typeName}s.{fieldName}?.Dispose();");
            }
        }
        writer.WriteLine("    }");

        writer.WriteLine("}");

        Log.Info($"Generated {path}");
    }

    private static void GenerateLua(EditorConfig config)
    {
        var path = config.GenerateLua!;
        var className = config.LuaClass;

        Directory.CreateDirectory(Path.GetDirectoryName(path) ?? ".");

        using var writer = new StreamWriter(path);

        writer.WriteLine("--");
        writer.WriteLine("--  Auto-generated by NoZ Editor - DO NOT EDIT");
        writer.WriteLine("--");
        writer.WriteLine();
        writer.WriteLine($"local {className} = {{}}");
        writer.WriteLine();

        var documentsByType = DocumentManager.Documents
            .Where(d => !d.IsEditorOnly)
            .GroupBy(d => d.Def.Type)
            .OrderBy(g => g.Key.ToString());

        foreach (var group in documentsByType)
        {
            var typeName = group.Key.ToString();
            writer.WriteLine($"{className}.{typeName}s = {{");

            foreach (var doc in group.OrderBy(d => d.Name))
            {
                var constName = ToPascalCase(doc.Name);
                writer.WriteLine($"    {constName} = \"{doc.Name}\",");
            }

            writer.WriteLine("}");
            writer.WriteLine();
        }

        writer.WriteLine($"return {className}");

        Log.Info($"Generated {path}");
    }

    private static string ToPascalCase(string name)
    {
        var sb = new System.Text.StringBuilder();
        var capitalizeNext = true;

        foreach (var c in name)
        {
            if (c == '_' || c == '-' || c == ' ')
            {
                capitalizeNext = true;
            }
            else if (capitalizeNext)
            {
                sb.Append(char.ToUpperInvariant(c));
                capitalizeNext = false;
            }
            else
            {
                sb.Append(c);
            }
        }

        return sb.ToString();
    }
}
