//
//  Auto-generated by NoZ Editor - DO NOT EDIT
//

namespace NoZ.Editor;

public static class EditorAssets
{
    public static class Names
    {
        public const string Composite = "composite";
        public const string Sprite = "sprite";
        public const string Text = "text";
        public const string Texture = "texture";
        public const string Ui = "ui";
        public const string AssetIconAtlas = "asset_icon_atlas";
        public const string AssetIconBin = "asset_icon_bin";
        public const string AssetIconEvent = "asset_icon_event";
        public const string AssetIconFont = "asset_icon_font";
        public const string AssetIconLua = "asset_icon_lua";
        public const string AssetIconShader = "asset_icon_shader";
        public const string AssetIconSound = "asset_icon_sound";
        public const string AssetIconVfx = "asset_icon_vfx";
        public const string IconCircle = "icon_circle";
        public const string IconClose = "icon_close";
        public const string IconDropdown = "icon_dropdown";
        public const string IconEdgeMode = "icon_edge_mode";
        public const string IconExpandDown = "icon_expand_down";
        public const string IconExpandUp = "icon_expand_up";
        public const string IconFaceMode = "icon_face_mode";
        public const string IconLoop = "icon_loop";
        public const string IconMirror = "icon_mirror";
        public const string IconOnion = "icon_onion";
        public const string IconOpacity = "icon_opacity";
        public const string IconOpacityOverlay = "icon_opacity_overlay";
        public const string IconPalette = "icon_palette";
        public const string IconPublish = "icon_publish";
        public const string IconRootMotion = "icon_root_motion";
        public const string IconSubmenu = "icon_submenu";
        public const string IconTiling = "icon_tiling";
        public const string IconVertexMode = "icon_vertex_mode";
        public const string IconWeightMode = "icon_weight_mode";
        public const string EditorPalette = "editor_palette";
    }

    public static class Shaders
    {
        public static Asset? Composite;
        public static Asset? Sprite;
        public static Asset? Text;
        public static Asset? Texture;
        public static Asset? Ui;
    }

    public static class Sprites
    {
        public static Asset? AssetIconAtlas;
        public static Asset? AssetIconBin;
        public static Asset? AssetIconEvent;
        public static Asset? AssetIconFont;
        public static Asset? AssetIconLua;
        public static Asset? AssetIconShader;
        public static Asset? AssetIconSound;
        public static Asset? AssetIconVfx;
        public static Asset? IconCircle;
        public static Asset? IconClose;
        public static Asset? IconDropdown;
        public static Asset? IconEdgeMode;
        public static Asset? IconExpandDown;
        public static Asset? IconExpandUp;
        public static Asset? IconFaceMode;
        public static Asset? IconLoop;
        public static Asset? IconMirror;
        public static Asset? IconOnion;
        public static Asset? IconOpacity;
        public static Asset? IconOpacityOverlay;
        public static Asset? IconPalette;
        public static Asset? IconPublish;
        public static Asset? IconRootMotion;
        public static Asset? IconSubmenu;
        public static Asset? IconTiling;
        public static Asset? IconVertexMode;
        public static Asset? IconWeightMode;
    }

    public static class Textures
    {
        public static Asset? EditorPalette;
    }

    public static void LoadAssets()
    {
        Shaders.Composite = (Asset?)Asset.Load(AssetType.Shader, Names.Composite);
        Shaders.Sprite = (Asset?)Asset.Load(AssetType.Shader, Names.Sprite);
        Shaders.Text = (Asset?)Asset.Load(AssetType.Shader, Names.Text);
        Shaders.Texture = (Asset?)Asset.Load(AssetType.Shader, Names.Texture);
        Shaders.Ui = (Asset?)Asset.Load(AssetType.Shader, Names.Ui);
        Sprites.AssetIconAtlas = (Asset?)Asset.Load(AssetType.Sprite, Names.AssetIconAtlas);
        Sprites.AssetIconBin = (Asset?)Asset.Load(AssetType.Sprite, Names.AssetIconBin);
        Sprites.AssetIconEvent = (Asset?)Asset.Load(AssetType.Sprite, Names.AssetIconEvent);
        Sprites.AssetIconFont = (Asset?)Asset.Load(AssetType.Sprite, Names.AssetIconFont);
        Sprites.AssetIconLua = (Asset?)Asset.Load(AssetType.Sprite, Names.AssetIconLua);
        Sprites.AssetIconShader = (Asset?)Asset.Load(AssetType.Sprite, Names.AssetIconShader);
        Sprites.AssetIconSound = (Asset?)Asset.Load(AssetType.Sprite, Names.AssetIconSound);
        Sprites.AssetIconVfx = (Asset?)Asset.Load(AssetType.Sprite, Names.AssetIconVfx);
        Sprites.IconCircle = (Asset?)Asset.Load(AssetType.Sprite, Names.IconCircle);
        Sprites.IconClose = (Asset?)Asset.Load(AssetType.Sprite, Names.IconClose);
        Sprites.IconDropdown = (Asset?)Asset.Load(AssetType.Sprite, Names.IconDropdown);
        Sprites.IconEdgeMode = (Asset?)Asset.Load(AssetType.Sprite, Names.IconEdgeMode);
        Sprites.IconExpandDown = (Asset?)Asset.Load(AssetType.Sprite, Names.IconExpandDown);
        Sprites.IconExpandUp = (Asset?)Asset.Load(AssetType.Sprite, Names.IconExpandUp);
        Sprites.IconFaceMode = (Asset?)Asset.Load(AssetType.Sprite, Names.IconFaceMode);
        Sprites.IconLoop = (Asset?)Asset.Load(AssetType.Sprite, Names.IconLoop);
        Sprites.IconMirror = (Asset?)Asset.Load(AssetType.Sprite, Names.IconMirror);
        Sprites.IconOnion = (Asset?)Asset.Load(AssetType.Sprite, Names.IconOnion);
        Sprites.IconOpacity = (Asset?)Asset.Load(AssetType.Sprite, Names.IconOpacity);
        Sprites.IconOpacityOverlay = (Asset?)Asset.Load(AssetType.Sprite, Names.IconOpacityOverlay);
        Sprites.IconPalette = (Asset?)Asset.Load(AssetType.Sprite, Names.IconPalette);
        Sprites.IconPublish = (Asset?)Asset.Load(AssetType.Sprite, Names.IconPublish);
        Sprites.IconRootMotion = (Asset?)Asset.Load(AssetType.Sprite, Names.IconRootMotion);
        Sprites.IconSubmenu = (Asset?)Asset.Load(AssetType.Sprite, Names.IconSubmenu);
        Sprites.IconTiling = (Asset?)Asset.Load(AssetType.Sprite, Names.IconTiling);
        Sprites.IconVertexMode = (Asset?)Asset.Load(AssetType.Sprite, Names.IconVertexMode);
        Sprites.IconWeightMode = (Asset?)Asset.Load(AssetType.Sprite, Names.IconWeightMode);
        Textures.EditorPalette = (Asset?)Asset.Load(AssetType.Texture, Names.EditorPalette);
    }

    public static void ReloadAssets()
    {
        // TODO: hot reload
    }

    public static void UnloadAssets()
    {
        Shaders.Composite?.Dispose();
        Shaders.Sprite?.Dispose();
        Shaders.Text?.Dispose();
        Shaders.Texture?.Dispose();
        Shaders.Ui?.Dispose();
        Sprites.AssetIconAtlas?.Dispose();
        Sprites.AssetIconBin?.Dispose();
        Sprites.AssetIconEvent?.Dispose();
        Sprites.AssetIconFont?.Dispose();
        Sprites.AssetIconLua?.Dispose();
        Sprites.AssetIconShader?.Dispose();
        Sprites.AssetIconSound?.Dispose();
        Sprites.AssetIconVfx?.Dispose();
        Sprites.IconCircle?.Dispose();
        Sprites.IconClose?.Dispose();
        Sprites.IconDropdown?.Dispose();
        Sprites.IconEdgeMode?.Dispose();
        Sprites.IconExpandDown?.Dispose();
        Sprites.IconExpandUp?.Dispose();
        Sprites.IconFaceMode?.Dispose();
        Sprites.IconLoop?.Dispose();
        Sprites.IconMirror?.Dispose();
        Sprites.IconOnion?.Dispose();
        Sprites.IconOpacity?.Dispose();
        Sprites.IconOpacityOverlay?.Dispose();
        Sprites.IconPalette?.Dispose();
        Sprites.IconPublish?.Dispose();
        Sprites.IconRootMotion?.Dispose();
        Sprites.IconSubmenu?.Dispose();
        Sprites.IconTiling?.Dispose();
        Sprites.IconVertexMode?.Dispose();
        Sprites.IconWeightMode?.Dispose();
        Textures.EditorPalette?.Dispose();
    }
}
