//
//  Auto-generated by NoZ Editor - DO NOT EDIT
//

using NoZ;

namespace NoZ.Editor;

public static class EditorAssets
{
    public static class Names
    {
        public const string EditorSprites000 = "editor_sprites000";
        public const string Seguisb = "seguisb";
        public const string Composite = "composite";
        public const string Sprite = "sprite";
        public const string Text = "text";
        public const string Texture = "texture";
        public const string Ui = "ui";
        public const string AssetIconAtlas = "asset_icon_atlas";
        public const string AssetIconBin = "asset_icon_bin";
        public const string AssetIconEvent = "asset_icon_event";
        public const string AssetIconFont = "asset_icon_font";
        public const string AssetIconLua = "asset_icon_lua";
        public const string AssetIconShader = "asset_icon_shader";
        public const string AssetIconSound = "asset_icon_sound";
        public const string AssetIconVfx = "asset_icon_vfx";
        public const string IconCircle = "icon_circle";
        public const string IconClose = "icon_close";
        public const string IconDropdown = "icon_dropdown";
        public const string IconEdgeMode = "icon_edge_mode";
        public const string IconExpandDown = "icon_expand_down";
        public const string IconExpandUp = "icon_expand_up";
        public const string IconFaceMode = "icon_face_mode";
        public const string IconLoop = "icon_loop";
        public const string IconMirror = "icon_mirror";
        public const string IconOnion = "icon_onion";
        public const string IconOpacity = "icon_opacity";
        public const string IconOpacityOverlay = "icon_opacity_overlay";
        public const string IconPalette = "icon_palette";
        public const string IconPublish = "icon_publish";
        public const string IconRootMotion = "icon_root_motion";
        public const string IconSearch = "icon_search";
        public const string IconSubmenu = "icon_submenu";
        public const string IconTiling = "icon_tiling";
        public const string IconVertexMode = "icon_vertex_mode";
        public const string IconWeightMode = "icon_weight_mode";
        public const string New = "new";
        public const string EditorPalette = "editor_palette";
    }

    public static class Atlases
    {
        public static Atlas EditorSprites000 { get; private set; } = null!;

        public static void Load()
        {
            EditorSprites000 = (Atlas)Asset.Load(AssetType.Atlas, Names.EditorSprites000)!;
        }

        public static void Unload()
        {
            EditorSprites000?.Dispose();
        }
    }

    public static class Fonts
    {
        public static Font Seguisb { get; private set; } = null!;

        public static void Load()
        {
            Seguisb = (Font)Asset.Load(AssetType.Font, Names.Seguisb)!;
        }

        public static void Unload()
        {
            Seguisb?.Dispose();
        }
    }

    public static class Shaders
    {
        public static Shader Composite { get; private set; } = null!;
        public static Shader Sprite { get; private set; } = null!;
        public static Shader Text { get; private set; } = null!;
        public static Shader Texture { get; private set; } = null!;
        public static Shader Ui { get; private set; } = null!;

        public static void Load()
        {
            Composite = (Shader)Asset.Load(AssetType.Shader, Names.Composite)!;
            Sprite = (Shader)Asset.Load(AssetType.Shader, Names.Sprite)!;
            Text = (Shader)Asset.Load(AssetType.Shader, Names.Text)!;
            Texture = (Shader)Asset.Load(AssetType.Shader, Names.Texture)!;
            Ui = (Shader)Asset.Load(AssetType.Shader, Names.Ui)!;
        }

        public static void Unload()
        {
            Composite?.Dispose();
            Sprite?.Dispose();
            Text?.Dispose();
            Texture?.Dispose();
            Ui?.Dispose();
        }
    }

    public static class Sprites
    {
        public static Sprite AssetIconAtlas { get; private set; } = null!;
        public static Sprite AssetIconBin { get; private set; } = null!;
        public static Sprite AssetIconEvent { get; private set; } = null!;
        public static Sprite AssetIconFont { get; private set; } = null!;
        public static Sprite AssetIconLua { get; private set; } = null!;
        public static Sprite AssetIconShader { get; private set; } = null!;
        public static Sprite AssetIconSound { get; private set; } = null!;
        public static Sprite AssetIconVfx { get; private set; } = null!;
        public static Sprite IconCircle { get; private set; } = null!;
        public static Sprite IconClose { get; private set; } = null!;
        public static Sprite IconDropdown { get; private set; } = null!;
        public static Sprite IconEdgeMode { get; private set; } = null!;
        public static Sprite IconExpandDown { get; private set; } = null!;
        public static Sprite IconExpandUp { get; private set; } = null!;
        public static Sprite IconFaceMode { get; private set; } = null!;
        public static Sprite IconLoop { get; private set; } = null!;
        public static Sprite IconMirror { get; private set; } = null!;
        public static Sprite IconOnion { get; private set; } = null!;
        public static Sprite IconOpacity { get; private set; } = null!;
        public static Sprite IconOpacityOverlay { get; private set; } = null!;
        public static Sprite IconPalette { get; private set; } = null!;
        public static Sprite IconPublish { get; private set; } = null!;
        public static Sprite IconRootMotion { get; private set; } = null!;
        public static Sprite IconSearch { get; private set; } = null!;
        public static Sprite IconSubmenu { get; private set; } = null!;
        public static Sprite IconTiling { get; private set; } = null!;
        public static Sprite IconVertexMode { get; private set; } = null!;
        public static Sprite IconWeightMode { get; private set; } = null!;
        public static Sprite New { get; private set; } = null!;

        public static void Load()
        {
            AssetIconAtlas = (Sprite)Asset.Load(AssetType.Sprite, Names.AssetIconAtlas)!;
            AssetIconBin = (Sprite)Asset.Load(AssetType.Sprite, Names.AssetIconBin)!;
            AssetIconEvent = (Sprite)Asset.Load(AssetType.Sprite, Names.AssetIconEvent)!;
            AssetIconFont = (Sprite)Asset.Load(AssetType.Sprite, Names.AssetIconFont)!;
            AssetIconLua = (Sprite)Asset.Load(AssetType.Sprite, Names.AssetIconLua)!;
            AssetIconShader = (Sprite)Asset.Load(AssetType.Sprite, Names.AssetIconShader)!;
            AssetIconSound = (Sprite)Asset.Load(AssetType.Sprite, Names.AssetIconSound)!;
            AssetIconVfx = (Sprite)Asset.Load(AssetType.Sprite, Names.AssetIconVfx)!;
            IconCircle = (Sprite)Asset.Load(AssetType.Sprite, Names.IconCircle)!;
            IconClose = (Sprite)Asset.Load(AssetType.Sprite, Names.IconClose)!;
            IconDropdown = (Sprite)Asset.Load(AssetType.Sprite, Names.IconDropdown)!;
            IconEdgeMode = (Sprite)Asset.Load(AssetType.Sprite, Names.IconEdgeMode)!;
            IconExpandDown = (Sprite)Asset.Load(AssetType.Sprite, Names.IconExpandDown)!;
            IconExpandUp = (Sprite)Asset.Load(AssetType.Sprite, Names.IconExpandUp)!;
            IconFaceMode = (Sprite)Asset.Load(AssetType.Sprite, Names.IconFaceMode)!;
            IconLoop = (Sprite)Asset.Load(AssetType.Sprite, Names.IconLoop)!;
            IconMirror = (Sprite)Asset.Load(AssetType.Sprite, Names.IconMirror)!;
            IconOnion = (Sprite)Asset.Load(AssetType.Sprite, Names.IconOnion)!;
            IconOpacity = (Sprite)Asset.Load(AssetType.Sprite, Names.IconOpacity)!;
            IconOpacityOverlay = (Sprite)Asset.Load(AssetType.Sprite, Names.IconOpacityOverlay)!;
            IconPalette = (Sprite)Asset.Load(AssetType.Sprite, Names.IconPalette)!;
            IconPublish = (Sprite)Asset.Load(AssetType.Sprite, Names.IconPublish)!;
            IconRootMotion = (Sprite)Asset.Load(AssetType.Sprite, Names.IconRootMotion)!;
            IconSearch = (Sprite)Asset.Load(AssetType.Sprite, Names.IconSearch)!;
            IconSubmenu = (Sprite)Asset.Load(AssetType.Sprite, Names.IconSubmenu)!;
            IconTiling = (Sprite)Asset.Load(AssetType.Sprite, Names.IconTiling)!;
            IconVertexMode = (Sprite)Asset.Load(AssetType.Sprite, Names.IconVertexMode)!;
            IconWeightMode = (Sprite)Asset.Load(AssetType.Sprite, Names.IconWeightMode)!;
            New = (Sprite)Asset.Load(AssetType.Sprite, Names.New)!;
        }

        public static void Unload()
        {
            AssetIconAtlas?.Dispose();
            AssetIconBin?.Dispose();
            AssetIconEvent?.Dispose();
            AssetIconFont?.Dispose();
            AssetIconLua?.Dispose();
            AssetIconShader?.Dispose();
            AssetIconSound?.Dispose();
            AssetIconVfx?.Dispose();
            IconCircle?.Dispose();
            IconClose?.Dispose();
            IconDropdown?.Dispose();
            IconEdgeMode?.Dispose();
            IconExpandDown?.Dispose();
            IconExpandUp?.Dispose();
            IconFaceMode?.Dispose();
            IconLoop?.Dispose();
            IconMirror?.Dispose();
            IconOnion?.Dispose();
            IconOpacity?.Dispose();
            IconOpacityOverlay?.Dispose();
            IconPalette?.Dispose();
            IconPublish?.Dispose();
            IconRootMotion?.Dispose();
            IconSearch?.Dispose();
            IconSubmenu?.Dispose();
            IconTiling?.Dispose();
            IconVertexMode?.Dispose();
            IconWeightMode?.Dispose();
            New?.Dispose();
        }
    }

    public static class Textures
    {
        public static Texture EditorPalette { get; private set; } = null!;

        public static void Load()
        {
            EditorPalette = (Texture)Asset.Load(AssetType.Texture, Names.EditorPalette)!;
        }

        public static void Unload()
        {
            EditorPalette?.Dispose();
        }
    }

    public static Texture? AtlasArray { get; private set; }

    public static void LoadAssets()
    {
        Atlases.Load();
        Fonts.Load();
        Shaders.Load();
        Sprites.Load();
        Textures.Load();

        // Create texture array from all atlases
        AtlasArray = Texture.CreateArray("SpriteAtlas",Atlases.EditorSprites000);
        Graphics.SpriteAtlas = AtlasArray;
    }

    public static void ReloadAssets()
    {
        // TODO: hot reload
    }

    public static void UnloadAssets()
    {
        Graphics.SpriteAtlas = null;
        AtlasArray?.Dispose();
        AtlasArray = null;
        Atlases.Unload();
        Fonts.Unload();
        Shaders.Unload();
        Sprites.Unload();
        Textures.Unload();
    }
}
