//
//  Auto-generated by NoZ Editor - DO NOT EDIT
//

using NoZ;

namespace NoZ.Editor;

public static class EditorAssets
{
    public static class Names
    {
        public const string AssetIconAnimation = "asset_icon_animation";
        public const string AssetIconAtlas = "asset_icon_atlas";
        public const string AssetIconBin = "asset_icon_bin";
        public const string AssetIconEvent = "asset_icon_event";
        public const string AssetIconFont = "asset_icon_font";
        public const string AssetIconGenstyle = "asset_icon_genstyle";
        public const string AssetIconShader = "asset_icon_shader";
        public const string AssetIconSound = "asset_icon_sound";
        public const string AssetIconSprite = "asset_icon_sprite";
        public const string AssetIconVfx = "asset_icon_vfx";
        public const string Circle = "circle";
        public const string CursorArrow = "cursor_arrow";
        public const string CursorBeam = "cursor_beam";
        public const string CursorCurve = "cursor_curve";
        public const string CursorDropper = "cursor_dropper";
        public const string CursorMove = "cursor_move";
        public const string CursorRotate = "cursor_rotate";
        public const string CursorScale = "cursor_scale";
        public const string EditorSprites000 = "editor_sprites000";
        public const string GizmoHandle = "gizmo_handle";
        public const string IconAdd = "icon_add";
        public const string IconAi = "icon_ai";
        public const string IconBone = "icon_bone";
        public const string IconCheck = "icon_check";
        public const string IconCircle = "icon_circle";
        public const string IconClip = "icon_clip";
        public const string IconClose = "icon_close";
        public const string IconCollection = "icon_collection";
        public const string IconConnected = "icon_connected";
        public const string IconConstraint = "icon_constraint";
        public const string IconDelete = "icon_delete";
        public const string IconDropdown = "icon_dropdown";
        public const string IconDuplicate = "icon_duplicate";
        public const string IconEdit = "icon_edit";
        public const string IconEmpty = "icon_empty";
        public const string IconEraser = "icon_eraser";
        public const string IconExpandDown = "icon_expand_down";
        public const string IconExpandUp = "icon_expand_up";
        public const string IconFill = "icon_fill";
        public const string IconFloodFill = "icon_flood_fill";
        public const string IconFoldoutClosed = "icon_foldout_closed";
        public const string IconFoldoutOpen = "icon_foldout_open";
        public const string IconGenerating = "icon_generating";
        public const string IconGradientLinear = "icon_gradient_linear";
        public const string IconHidden = "icon_hidden";
        public const string IconKeyframe = "icon_keyframe";
        public const string IconLayer = "icon_layer";
        public const string IconLock = "icon_lock";
        public const string IconLoop = "icon_loop";
        public const string IconMenu = "icon_menu";
        public const string IconMirror = "icon_mirror";
        public const string IconMove = "icon_move";
        public const string IconNofill = "icon_nofill";
        public const string IconOnion = "icon_onion";
        public const string IconOpacity = "icon_opacity";
        public const string IconOpacityOverlay = "icon_opacity_overlay";
        public const string IconPalette = "icon_palette";
        public const string IconPath = "icon_path";
        public const string IconPathLayer = "icon_path_layer";
        public const string IconPlay = "icon_play";
        public const string IconPreview = "icon_preview";
        public const string IconPublish = "icon_publish";
        public const string IconRandom = "icon_random";
        public const string IconRandomRange = "icon_random_range";
        public const string IconRasterize = "icon_rasterize";
        public const string IconRefresh = "icon_refresh";
        public const string IconRemove = "icon_remove";
        public const string IconRootMotion = "icon_root_motion";
        public const string IconScrub = "icon_scrub";
        public const string IconSearch = "icon_search";
        public const string IconSeed = "icon_seed";
        public const string IconSelect = "icon_select";
        public const string IconSort = "icon_sort";
        public const string IconStroke = "icon_stroke";
        public const string IconStrokeJoinBevel = "icon_stroke_join_bevel";
        public const string IconStrokeJoinMiter = "icon_stroke_join_miter";
        public const string IconStrokeJoinRound = "icon_stroke_join_round";
        public const string IconStrokeSize = "icon_stroke_size";
        public const string IconSubmenu = "icon_submenu";
        public const string IconSubtract = "icon_subtract";
        public const string IconTiling = "icon_tiling";
        public const string IconUnlock = "icon_unlock";
        public const string IconXray = "icon_xray";
        public const string PpComposite = "pp_composite";
        public const string PpDownsample = "pp_downsample";
        public const string PpUpsample = "pp_upsample";
        public const string Seguisb = "seguisb";
        public const string Sprite = "sprite";
        public const string Square = "square";
        public const string Star = "star";
        public const string Text = "text";
        public const string Texture = "texture";
        public const string Ui = "ui";
    }

    public static class Atlases
    {
        public static readonly Atlas EditorSprites000 = new();

        public static void Load()
        {
            EditorSprites000.Load(Names.EditorSprites000);
        }

        public static void Reload()
        {
            EditorSprites000.Reload();
        }

        public static void Unload()
        {
            EditorSprites000.Dispose();
        }
    }

    public static class Fonts
    {
        public static readonly Font Seguisb = new();

        public static void Load()
        {
            Seguisb.Load(Names.Seguisb);
        }

        public static void Reload()
        {
            Seguisb.Reload();
        }

        public static void Unload()
        {
            Seguisb.Dispose();
        }
    }

    public static class Shaders
    {
        public static readonly Shader PpComposite = new();
        public static readonly Shader PpDownsample = new();
        public static readonly Shader PpUpsample = new();
        public static readonly Shader Sprite = new();
        public static readonly Shader Text = new();
        public static readonly Shader Texture = new();
        public static readonly Shader Ui = new();

        public static void Load()
        {
            PpComposite.Load(Names.PpComposite);
            PpDownsample.Load(Names.PpDownsample);
            PpUpsample.Load(Names.PpUpsample);
            Sprite.Load(Names.Sprite);
            Text.Load(Names.Text);
            Texture.Load(Names.Texture);
            Ui.Load(Names.Ui);
        }

        public static void Reload()
        {
            PpComposite.Reload();
            PpDownsample.Reload();
            PpUpsample.Reload();
            Sprite.Reload();
            Text.Reload();
            Texture.Reload();
            Ui.Reload();
        }

        public static void Unload()
        {
            PpComposite.Dispose();
            PpDownsample.Dispose();
            PpUpsample.Dispose();
            Sprite.Dispose();
            Text.Dispose();
            Texture.Dispose();
            Ui.Dispose();
        }
    }

    public static class Sprites
    {
        public static readonly Sprite AssetIconAnimation = new();
        public static readonly Sprite AssetIconAtlas = new();
        public static readonly Sprite AssetIconBin = new();
        public static readonly Sprite AssetIconEvent = new();
        public static readonly Sprite AssetIconFont = new();
        public static readonly Sprite AssetIconGenstyle = new();
        public static readonly Sprite AssetIconShader = new();
        public static readonly Sprite AssetIconSound = new();
        public static readonly Sprite AssetIconSprite = new();
        public static readonly Sprite AssetIconVfx = new();
        public static readonly Sprite Circle = new();
        public static readonly Sprite CursorArrow = new();
        public static readonly Sprite CursorBeam = new();
        public static readonly Sprite CursorCurve = new();
        public static readonly Sprite CursorDropper = new();
        public static readonly Sprite CursorMove = new();
        public static readonly Sprite CursorRotate = new();
        public static readonly Sprite CursorScale = new();
        public static readonly Sprite GizmoHandle = new();
        public static readonly Sprite IconAdd = new();
        public static readonly Sprite IconAi = new();
        public static readonly Sprite IconBone = new();
        public static readonly Sprite IconCheck = new();
        public static readonly Sprite IconCircle = new();
        public static readonly Sprite IconClip = new();
        public static readonly Sprite IconClose = new();
        public static readonly Sprite IconCollection = new();
        public static readonly Sprite IconConnected = new();
        public static readonly Sprite IconConstraint = new();
        public static readonly Sprite IconDelete = new();
        public static readonly Sprite IconDropdown = new();
        public static readonly Sprite IconDuplicate = new();
        public static readonly Sprite IconEdit = new();
        public static readonly Sprite IconEmpty = new();
        public static readonly Sprite IconEraser = new();
        public static readonly Sprite IconExpandDown = new();
        public static readonly Sprite IconExpandUp = new();
        public static readonly Sprite IconFill = new();
        public static readonly Sprite IconFloodFill = new();
        public static readonly Sprite IconFoldoutClosed = new();
        public static readonly Sprite IconFoldoutOpen = new();
        public static readonly Sprite IconGenerating = new();
        public static readonly Sprite IconGradientLinear = new();
        public static readonly Sprite IconHidden = new();
        public static readonly Sprite IconKeyframe = new();
        public static readonly Sprite IconLayer = new();
        public static readonly Sprite IconLock = new();
        public static readonly Sprite IconLoop = new();
        public static readonly Sprite IconMenu = new();
        public static readonly Sprite IconMirror = new();
        public static readonly Sprite IconMove = new();
        public static readonly Sprite IconNofill = new();
        public static readonly Sprite IconOnion = new();
        public static readonly Sprite IconOpacity = new();
        public static readonly Sprite IconOpacityOverlay = new();
        public static readonly Sprite IconPalette = new();
        public static readonly Sprite IconPath = new();
        public static readonly Sprite IconPathLayer = new();
        public static readonly Sprite IconPlay = new();
        public static readonly Sprite IconPreview = new();
        public static readonly Sprite IconPublish = new();
        public static readonly Sprite IconRandom = new();
        public static readonly Sprite IconRandomRange = new();
        public static readonly Sprite IconRasterize = new();
        public static readonly Sprite IconRefresh = new();
        public static readonly Sprite IconRemove = new();
        public static readonly Sprite IconRootMotion = new();
        public static readonly Sprite IconScrub = new();
        public static readonly Sprite IconSearch = new();
        public static readonly Sprite IconSeed = new();
        public static readonly Sprite IconSelect = new();
        public static readonly Sprite IconSort = new();
        public static readonly Sprite IconStroke = new();
        public static readonly Sprite IconStrokeJoinBevel = new();
        public static readonly Sprite IconStrokeJoinMiter = new();
        public static readonly Sprite IconStrokeJoinRound = new();
        public static readonly Sprite IconStrokeSize = new();
        public static readonly Sprite IconSubmenu = new();
        public static readonly Sprite IconSubtract = new();
        public static readonly Sprite IconTiling = new();
        public static readonly Sprite IconUnlock = new();
        public static readonly Sprite IconXray = new();
        public static readonly Sprite Square = new();
        public static readonly Sprite Star = new();

        public static void Load(Texture atlas)
        {
            AssetIconAnimation.Load(Names.AssetIconAnimation, atlas);
            AssetIconAtlas.Load(Names.AssetIconAtlas, atlas);
            AssetIconBin.Load(Names.AssetIconBin, atlas);
            AssetIconEvent.Load(Names.AssetIconEvent, atlas);
            AssetIconFont.Load(Names.AssetIconFont, atlas);
            AssetIconGenstyle.Load(Names.AssetIconGenstyle, atlas);
            AssetIconShader.Load(Names.AssetIconShader, atlas);
            AssetIconSound.Load(Names.AssetIconSound, atlas);
            AssetIconSprite.Load(Names.AssetIconSprite, atlas);
            AssetIconVfx.Load(Names.AssetIconVfx, atlas);
            Circle.Load(Names.Circle, atlas);
            CursorArrow.Load(Names.CursorArrow, atlas);
            CursorBeam.Load(Names.CursorBeam, atlas);
            CursorCurve.Load(Names.CursorCurve, atlas);
            CursorDropper.Load(Names.CursorDropper, atlas);
            CursorMove.Load(Names.CursorMove, atlas);
            CursorRotate.Load(Names.CursorRotate, atlas);
            CursorScale.Load(Names.CursorScale, atlas);
            GizmoHandle.Load(Names.GizmoHandle, atlas);
            IconAdd.Load(Names.IconAdd, atlas);
            IconAi.Load(Names.IconAi, atlas);
            IconBone.Load(Names.IconBone, atlas);
            IconCheck.Load(Names.IconCheck, atlas);
            IconCircle.Load(Names.IconCircle, atlas);
            IconClip.Load(Names.IconClip, atlas);
            IconClose.Load(Names.IconClose, atlas);
            IconCollection.Load(Names.IconCollection, atlas);
            IconConnected.Load(Names.IconConnected, atlas);
            IconConstraint.Load(Names.IconConstraint, atlas);
            IconDelete.Load(Names.IconDelete, atlas);
            IconDropdown.Load(Names.IconDropdown, atlas);
            IconDuplicate.Load(Names.IconDuplicate, atlas);
            IconEdit.Load(Names.IconEdit, atlas);
            IconEmpty.Load(Names.IconEmpty, atlas);
            IconEraser.Load(Names.IconEraser, atlas);
            IconExpandDown.Load(Names.IconExpandDown, atlas);
            IconExpandUp.Load(Names.IconExpandUp, atlas);
            IconFill.Load(Names.IconFill, atlas);
            IconFloodFill.Load(Names.IconFloodFill, atlas);
            IconFoldoutClosed.Load(Names.IconFoldoutClosed, atlas);
            IconFoldoutOpen.Load(Names.IconFoldoutOpen, atlas);
            IconGenerating.Load(Names.IconGenerating, atlas);
            IconGradientLinear.Load(Names.IconGradientLinear, atlas);
            IconHidden.Load(Names.IconHidden, atlas);
            IconKeyframe.Load(Names.IconKeyframe, atlas);
            IconLayer.Load(Names.IconLayer, atlas);
            IconLock.Load(Names.IconLock, atlas);
            IconLoop.Load(Names.IconLoop, atlas);
            IconMenu.Load(Names.IconMenu, atlas);
            IconMirror.Load(Names.IconMirror, atlas);
            IconMove.Load(Names.IconMove, atlas);
            IconNofill.Load(Names.IconNofill, atlas);
            IconOnion.Load(Names.IconOnion, atlas);
            IconOpacity.Load(Names.IconOpacity, atlas);
            IconOpacityOverlay.Load(Names.IconOpacityOverlay, atlas);
            IconPalette.Load(Names.IconPalette, atlas);
            IconPath.Load(Names.IconPath, atlas);
            IconPathLayer.Load(Names.IconPathLayer, atlas);
            IconPlay.Load(Names.IconPlay, atlas);
            IconPreview.Load(Names.IconPreview, atlas);
            IconPublish.Load(Names.IconPublish, atlas);
            IconRandom.Load(Names.IconRandom, atlas);
            IconRandomRange.Load(Names.IconRandomRange, atlas);
            IconRasterize.Load(Names.IconRasterize, atlas);
            IconRefresh.Load(Names.IconRefresh, atlas);
            IconRemove.Load(Names.IconRemove, atlas);
            IconRootMotion.Load(Names.IconRootMotion, atlas);
            IconScrub.Load(Names.IconScrub, atlas);
            IconSearch.Load(Names.IconSearch, atlas);
            IconSeed.Load(Names.IconSeed, atlas);
            IconSelect.Load(Names.IconSelect, atlas);
            IconSort.Load(Names.IconSort, atlas);
            IconStroke.Load(Names.IconStroke, atlas);
            IconStrokeJoinBevel.Load(Names.IconStrokeJoinBevel, atlas);
            IconStrokeJoinMiter.Load(Names.IconStrokeJoinMiter, atlas);
            IconStrokeJoinRound.Load(Names.IconStrokeJoinRound, atlas);
            IconStrokeSize.Load(Names.IconStrokeSize, atlas);
            IconSubmenu.Load(Names.IconSubmenu, atlas);
            IconSubtract.Load(Names.IconSubtract, atlas);
            IconTiling.Load(Names.IconTiling, atlas);
            IconUnlock.Load(Names.IconUnlock, atlas);
            IconXray.Load(Names.IconXray, atlas);
            Square.Load(Names.Square, atlas);
            Star.Load(Names.Star, atlas);
        }

        public static void Reload()
        {
            AssetIconAnimation.Reload();
            AssetIconAtlas.Reload();
            AssetIconBin.Reload();
            AssetIconEvent.Reload();
            AssetIconFont.Reload();
            AssetIconGenstyle.Reload();
            AssetIconShader.Reload();
            AssetIconSound.Reload();
            AssetIconSprite.Reload();
            AssetIconVfx.Reload();
            Circle.Reload();
            CursorArrow.Reload();
            CursorBeam.Reload();
            CursorCurve.Reload();
            CursorDropper.Reload();
            CursorMove.Reload();
            CursorRotate.Reload();
            CursorScale.Reload();
            GizmoHandle.Reload();
            IconAdd.Reload();
            IconAi.Reload();
            IconBone.Reload();
            IconCheck.Reload();
            IconCircle.Reload();
            IconClip.Reload();
            IconClose.Reload();
            IconCollection.Reload();
            IconConnected.Reload();
            IconConstraint.Reload();
            IconDelete.Reload();
            IconDropdown.Reload();
            IconDuplicate.Reload();
            IconEdit.Reload();
            IconEmpty.Reload();
            IconEraser.Reload();
            IconExpandDown.Reload();
            IconExpandUp.Reload();
            IconFill.Reload();
            IconFloodFill.Reload();
            IconFoldoutClosed.Reload();
            IconFoldoutOpen.Reload();
            IconGenerating.Reload();
            IconGradientLinear.Reload();
            IconHidden.Reload();
            IconKeyframe.Reload();
            IconLayer.Reload();
            IconLock.Reload();
            IconLoop.Reload();
            IconMenu.Reload();
            IconMirror.Reload();
            IconMove.Reload();
            IconNofill.Reload();
            IconOnion.Reload();
            IconOpacity.Reload();
            IconOpacityOverlay.Reload();
            IconPalette.Reload();
            IconPath.Reload();
            IconPathLayer.Reload();
            IconPlay.Reload();
            IconPreview.Reload();
            IconPublish.Reload();
            IconRandom.Reload();
            IconRandomRange.Reload();
            IconRasterize.Reload();
            IconRefresh.Reload();
            IconRemove.Reload();
            IconRootMotion.Reload();
            IconScrub.Reload();
            IconSearch.Reload();
            IconSeed.Reload();
            IconSelect.Reload();
            IconSort.Reload();
            IconStroke.Reload();
            IconStrokeJoinBevel.Reload();
            IconStrokeJoinMiter.Reload();
            IconStrokeJoinRound.Reload();
            IconStrokeSize.Reload();
            IconSubmenu.Reload();
            IconSubtract.Reload();
            IconTiling.Reload();
            IconUnlock.Reload();
            IconXray.Reload();
            Square.Reload();
            Star.Reload();
        }

        public static void Unload()
        {
            AssetIconAnimation.Dispose();
            AssetIconAtlas.Dispose();
            AssetIconBin.Dispose();
            AssetIconEvent.Dispose();
            AssetIconFont.Dispose();
            AssetIconGenstyle.Dispose();
            AssetIconShader.Dispose();
            AssetIconSound.Dispose();
            AssetIconSprite.Dispose();
            AssetIconVfx.Dispose();
            Circle.Dispose();
            CursorArrow.Dispose();
            CursorBeam.Dispose();
            CursorCurve.Dispose();
            CursorDropper.Dispose();
            CursorMove.Dispose();
            CursorRotate.Dispose();
            CursorScale.Dispose();
            GizmoHandle.Dispose();
            IconAdd.Dispose();
            IconAi.Dispose();
            IconBone.Dispose();
            IconCheck.Dispose();
            IconCircle.Dispose();
            IconClip.Dispose();
            IconClose.Dispose();
            IconCollection.Dispose();
            IconConnected.Dispose();
            IconConstraint.Dispose();
            IconDelete.Dispose();
            IconDropdown.Dispose();
            IconDuplicate.Dispose();
            IconEdit.Dispose();
            IconEmpty.Dispose();
            IconEraser.Dispose();
            IconExpandDown.Dispose();
            IconExpandUp.Dispose();
            IconFill.Dispose();
            IconFloodFill.Dispose();
            IconFoldoutClosed.Dispose();
            IconFoldoutOpen.Dispose();
            IconGenerating.Dispose();
            IconGradientLinear.Dispose();
            IconHidden.Dispose();
            IconKeyframe.Dispose();
            IconLayer.Dispose();
            IconLock.Dispose();
            IconLoop.Dispose();
            IconMenu.Dispose();
            IconMirror.Dispose();
            IconMove.Dispose();
            IconNofill.Dispose();
            IconOnion.Dispose();
            IconOpacity.Dispose();
            IconOpacityOverlay.Dispose();
            IconPalette.Dispose();
            IconPath.Dispose();
            IconPathLayer.Dispose();
            IconPlay.Dispose();
            IconPreview.Dispose();
            IconPublish.Dispose();
            IconRandom.Dispose();
            IconRandomRange.Dispose();
            IconRasterize.Dispose();
            IconRefresh.Dispose();
            IconRemove.Dispose();
            IconRootMotion.Dispose();
            IconScrub.Dispose();
            IconSearch.Dispose();
            IconSeed.Dispose();
            IconSelect.Dispose();
            IconSort.Dispose();
            IconStroke.Dispose();
            IconStrokeJoinBevel.Dispose();
            IconStrokeJoinMiter.Dispose();
            IconStrokeJoinRound.Dispose();
            IconStrokeSize.Dispose();
            IconSubmenu.Dispose();
            IconSubtract.Dispose();
            IconTiling.Dispose();
            IconUnlock.Dispose();
            IconXray.Dispose();
            Square.Dispose();
            Star.Dispose();
        }
    }

    public static Texture? AtlasArray { get; private set; }

    public static void LoadAssets()
    {
        Atlases.Load();
        AtlasArray = Texture.CreateArray("SpriteAtlas", Atlases.EditorSprites000);

        Fonts.Load();
        Shaders.Load();
        Sprites.Load(AtlasArray!);
    }

    public static void ReloadAssets()
    {
        Atlases.Reload();
        Fonts.Reload();
        Shaders.Reload();
        Sprites.Reload();
    }

    public static void UnloadAssets()
    {
        AtlasArray?.Dispose();
        AtlasArray = null;
        Atlases.Unload();
        Fonts.Unload();
        Shaders.Unload();
        Sprites.Unload();
    }
}
