//
//  NoZ - Copyright(c) 2026 NoZ Games, LLC
//

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace NoZ.Generators;

[Generator]
public class LocaleGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with [Localizable] attribute
        var classDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "NoZ.LocalizableAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetLocalizableInfo(ctx))
            .Where(static info => info is not null);

        // Find CSV files from AdditionalTexts
        var csvFiles = context.AdditionalTextsProvider
            .Where(static file => file.Path.EndsWith(".csv"));

        // Combine: pair each [Localizable] class with all CSV files
        var combined = classDeclarations.Combine(csvFiles.Collect());

        // Generate
        context.RegisterSourceOutput(combined, static (ctx, pair) =>
        {
            var info = pair.Left;
            var files = pair.Right;
            if (info is null) return;
            GenerateSource(ctx, info, files);
        });
    }

    private static LocalizableInfo? GetLocalizableInfo(GeneratorAttributeSyntaxContext context)
    {
        var symbol = context.TargetSymbol as INamedTypeSymbol;
        if (symbol is null) return null;

        return new LocalizableInfo
        {
            Namespace = symbol.ContainingNamespace.ToDisplayString(),
            ClassName = symbol.Name
        };
    }

    private static void GenerateSource(
        SourceProductionContext ctx,
        LocalizableInfo info,
        ImmutableArray<AdditionalText> csvFiles)
    {
        // Find the strings.csv file
        AdditionalText? stringsFile = null;
        foreach (var file in csvFiles)
        {
            if (file.Path.EndsWith("strings.csv"))
            {
                stringsFile = file;
                break;
            }
        }

        if (stringsFile is null) return;

        var text = stringsFile.GetText(ctx.CancellationToken)?.ToString();
        if (string.IsNullOrEmpty(text)) return;

        var csv = ParseCsv(text!);
        if (csv is null || csv.Entries.Count == 0) return;

        var defaultLocale = csv.Locales[0].Code;
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace) && info.Namespace != "<global namespace>")
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {info.ClassName}");
        sb.AppendLine("{");

        // Locales class with const names and All array
        sb.AppendLine("    public static class Locales");
        sb.AppendLine("    {");
        foreach (var locale in csv.Locales)
        {
            var constName = CapitalizeFirst(locale.Code);
            sb.AppendLine($"        public const string {constName} = \"{locale.Code}\";");
        }
        sb.AppendLine();
        sb.AppendLine("        public static readonly (string Code, string Name)[] All = new[]");
        sb.AppendLine("        {");
        foreach (var locale in csv.Locales)
        {
            var constName = CapitalizeFirst(locale.Code);
            sb.AppendLine($"            ({constName}, {EscapeString(locale.Name)}),");
        }
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();

        // CurrentLocale, CurrentLocaleName, CurrentLocaleIndex properties
        sb.AppendLine("    public static string CurrentLocale { get; private set; }");
        sb.AppendLine("    public static string CurrentLocaleName { get; private set; }");
        sb.AppendLine("    public static int CurrentLocaleIndex { get; private set; }");
        sb.AppendLine();

        // Static string properties with default values from first locale
        foreach (var entry in csv.Entries)
        {
            var defaultValue = entry.Values.ContainsKey(defaultLocale)
                ? entry.Values[defaultLocale]
                : "";
            sb.AppendLine($"    public static string {entry.Key} {{ get; private set; }} = {EscapeString(defaultValue)};");
        }
        sb.AppendLine();

        // SetLocale method
        sb.AppendLine("    public static void SetLocale(string locale)");
        sb.AppendLine("    {");
        sb.AppendLine("        CurrentLocale = locale;");

        bool first = true;
        int localeIndex = 0;
        foreach (var locale in csv.Locales)
        {
            var constName = CapitalizeFirst(locale.Code);
            var prefix = first ? "if" : "else if";
            sb.AppendLine($"        {prefix} (locale == Locales.{constName})");
            sb.AppendLine("        {");
            sb.AppendLine($"            CurrentLocaleName = {EscapeString(locale.Name)};");
            sb.AppendLine($"            CurrentLocaleIndex = {localeIndex};");

            foreach (var entry in csv.Entries)
            {
                var value = entry.Values.ContainsKey(locale.Code)
                    ? entry.Values[locale.Code]
                    : "";
                sb.AppendLine($"            {entry.Key} = {EscapeString(value)};");
            }

            sb.AppendLine("        }");
            first = false;
            localeIndex++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{info.ClassName}.Locale.g.cs", sb.ToString());
    }

    private static CsvData? ParseCsv(string text)
    {
        var lines = text.Split(new[] { "\r\n", "\n" }, System.StringSplitOptions.None);
        if (lines.Length < 2) return null;

        var header = ParseCsvLine(lines[0]);
        if (header.Count < 2) return null;

        // Parse header columns: "en:English" -> code="en", name="English"
        var locales = new List<LocaleInfo>();
        for (int i = 1; i < header.Count; i++)
        {
            var col = header[i].Trim();
            var colonIdx = col.IndexOf(':');
            if (colonIdx >= 0)
            {
                locales.Add(new LocaleInfo
                {
                    Code = col.Substring(0, colonIdx).Trim(),
                    Name = col.Substring(colonIdx + 1).Trim()
                });
            }
            else
            {
                locales.Add(new LocaleInfo
                {
                    Code = col,
                    Name = CapitalizeFirst(col)
                });
            }
        }

        var entries = new List<CsvEntry>();
        for (int i = 1; i < lines.Length; i++)
        {
            var line = lines[i].Trim();
            if (string.IsNullOrEmpty(line)) continue;

            var fields = ParseCsvLine(line);
            if (fields.Count < 2) continue;

            var key = fields[0].Trim();
            if (string.IsNullOrEmpty(key)) continue;

            var values = new Dictionary<string, string>();
            for (int j = 1; j < fields.Count && j <= locales.Count; j++)
                values[locales[j - 1].Code] = fields[j].Trim();

            entries.Add(new CsvEntry { Key = key, Values = values });
        }

        return new CsvData { Locales = locales, Entries = entries };
    }

    private static List<string> ParseCsvLine(string line)
    {
        var fields = new List<string>();
        var sb = new StringBuilder();
        bool inQuotes = false;
        int i = 0;

        while (i < line.Length)
        {
            char c = line[i];
            if (inQuotes)
            {
                if (c == '"')
                {
                    if (i + 1 < line.Length && line[i + 1] == '"')
                    {
                        sb.Append('"');
                        i += 2;
                    }
                    else
                    {
                        inQuotes = false;
                        i++;
                    }
                }
                else
                {
                    sb.Append(c);
                    i++;
                }
            }
            else
            {
                if (c == '"')
                {
                    inQuotes = true;
                    i++;
                }
                else if (c == ',')
                {
                    fields.Add(sb.ToString());
                    sb.Clear();
                    i++;
                }
                else
                {
                    sb.Append(c);
                    i++;
                }
            }
        }

        fields.Add(sb.ToString());
        return fields;
    }

    private static string EscapeString(string value)
    {
        return "\"" + value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r") + "\"";
    }

    private static string CapitalizeFirst(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        return char.ToUpperInvariant(s[0]) + s.Substring(1);
    }

    private class LocalizableInfo
    {
        public string Namespace { get; set; } = "";
        public string ClassName { get; set; } = "";
    }

    private class LocaleInfo
    {
        public string Code { get; set; } = "";
        public string Name { get; set; } = "";
    }

    private class CsvData
    {
        public List<LocaleInfo> Locales { get; set; } = new List<LocaleInfo>();
        public List<CsvEntry> Entries { get; set; } = new List<CsvEntry>();
    }

    private class CsvEntry
    {
        public string Key { get; set; } = "";
        public Dictionary<string, string> Values { get; set; } = new Dictionary<string, string>();
    }
}
