//
//  NoZ - Copyright(c) 2026 NoZ Games, LLC
//

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Text;

namespace NoZ.Generators;

[Generator]
public class WidgetIdGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all partial properties of type WidgetId
        var propertyDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is PropertyDeclarationSyntax prop &&
                    prop.Type.ToString() == "WidgetId" &&
                    prop.Modifiers.Any(m => m.Text == "partial"),
                transform: static (ctx, _) => GetPropertyInfo(ctx))
            .Where(static info => info is not null);

        // Group by containing class
        var grouped = propertyDeclarations
            .Collect()
            .Select(static (props, _) => props
                .Where(p => p is not null)
                .Cast<PropertyInfo>()
                .GroupBy(p => p.ClassKey)
                .Select(g => new ClassInfo
                {
                    Namespace = g.First().Namespace,
                    ClassName = g.First().ClassName,
                    ContainingTypes = g.First().ContainingTypes,
                    Properties = g.ToList()
                })
                .ToImmutableArray());

        context.RegisterSourceOutput(grouped, GenerateSource);
    }

    private static PropertyInfo? GetPropertyInfo(GeneratorSyntaxContext context)
    {
        var propSymbol = context.SemanticModel.GetDeclaredSymbol(context.Node) as IPropertySymbol;
        if (propSymbol is null) return null;

        // Must be a WidgetId property
        if (propSymbol.Type.Name != "WidgetId")
            return null;

        // Build containing type chain (for nested classes)
        var containingTypes = new List<ContainingTypeInfo>();
        var current = propSymbol.ContainingType?.ContainingType;
        while (current != null)
        {
            containingTypes.Insert(0, new ContainingTypeInfo
            {
                Name = current.Name,
                IsStatic = current.IsStatic
            });
            current = current.ContainingType;
        }

        var containingType = propSymbol.ContainingType;
        var ns = containingType?.ContainingNamespace?.ToDisplayString() ?? "";

        // Fully qualified name for hashing: "Namespace.ContainingTypes.ClassName.PropertyName"
        var containingTypeNames = containingTypes.Select(ct => ct.Name);

        var fullyQualifiedName = string.Join(".",
            new[] { ns }
                .Concat(containingTypeNames)
                .Concat(new[] { containingType?.Name ?? "", propSymbol.Name })
                .Where(s => !string.IsNullOrEmpty(s) && s != "<global namespace>"));

        var classKey = string.Join(".",
            new[] { ns }
                .Concat(containingTypeNames)
                .Append(containingType?.Name ?? "")
                .Where(s => !string.IsNullOrEmpty(s) && s != "<global namespace>"));

        return new PropertyInfo
        {
            Name = propSymbol.Name,
            Namespace = ns,
            ClassName = containingType?.Name ?? "",
            ContainingTypes = containingTypes,
            ClassKey = classKey,
            FullyQualifiedName = fullyQualifiedName
        };
    }

    private static void GenerateSource(
        SourceProductionContext context,
        ImmutableArray<ClassInfo> classes)
    {
        foreach (var classInfo in classes)
        {
            var source = GenerateClass(classInfo);

            var fileName = classInfo.ContainingTypes.Count > 0
                ? $"{string.Join(".", classInfo.ContainingTypes.Select(ct => ct.Name))}.{classInfo.ClassName}.g.cs"
                : $"{classInfo.ClassName}.g.cs";

            context.AddSource(fileName, source);
        }
    }

    private static string GenerateClass(ClassInfo info)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(info.Namespace) && info.Namespace != "<global namespace>")
        {
            sb.AppendLine($"namespace {info.Namespace};");
            sb.AppendLine();
        }

        // Open containing types
        var indent = "";
        foreach (var containingType in info.ContainingTypes)
        {
            var staticMod = containingType.IsStatic ? "static " : "";
            sb.AppendLine($"{indent}{staticMod}partial class {containingType.Name}");
            sb.AppendLine($"{indent}{{");
            indent += "    ";
        }

        // The target class
        sb.AppendLine($"{indent}static partial class {info.ClassName}");
        sb.AppendLine($"{indent}{{");
        indent += "    ";

        foreach (var prop in info.Properties)
        {
            // FNV-1a hash of fully qualified name
            ulong hash = Fnv1a(prop.FullyQualifiedName);

            // 48 bit name hash in upper bits, lower 16 bits = 0 (index space)
            ulong baseId = hash & 0xFFFFFFFFFFFF0000UL;

            // Never emit 0
            if (baseId == 0) baseId = 0x0000000000010000UL;

            sb.AppendLine($"{indent}// {prop.FullyQualifiedName}");
            sb.AppendLine($"{indent}public static partial NoZ.WidgetId {prop.Name} => new(0x{baseId:X16}UL);");
            sb.AppendLine();
        }

        // Close the target class
        indent = indent.Substring(4);
        sb.AppendLine($"{indent}}}");

        // Close containing types
        foreach (var _ in info.ContainingTypes)
        {
            indent = indent.Substring(4);
            sb.AppendLine($"{indent}}}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// FNV-1a 64-bit hash. Stable, deterministic, no dependencies.
    /// </summary>
    private static ulong Fnv1a(string text)
    {
        ulong hash = 14695981039346656037UL;
        foreach (char c in text)
        {
            hash ^= (byte)c;
            hash *= 1099511628211UL;
        }
        return hash;
    }

    private class ContainingTypeInfo
    {
        public string Name { get; set; } = "";
        public bool IsStatic { get; set; }
    }

    private class PropertyInfo
    {
        public string Name { get; set; } = "";
        public string Namespace { get; set; } = "";
        public string ClassName { get; set; } = "";
        public string ClassKey { get; set; } = "";
        public string FullyQualifiedName { get; set; } = "";
        public List<ContainingTypeInfo> ContainingTypes { get; set; } = new();
    }

    private class ClassInfo
    {
        public string Namespace { get; set; } = "";
        public string ClassName { get; set; } = "";
        public List<PropertyInfo> Properties { get; set; } = new();
        public List<ContainingTypeInfo> ContainingTypes { get; set; } = new();
    }
}