<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>NoZ.Editor.Graphics3D</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\NoZ.Editor.csproj" />
    <ProjectReference Include="..\..\..\engine\ext\graphics3d\NoZ.Graphics3D.csproj" />
    <ProjectReference Include="..\..\..\generators\NoZ.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>
</Project>
